default_stages: [ commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^migrations/
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: double-quote-string-fixer

  #  - repo: https://github.com/psf/black
#    rev: 23.10.0
#    hooks:
#      - id: black

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: /Users/sarit/.pyenv/versions/3.12.2/envs/try_fastapi/bin/pylint
      exclude: ^(migrations|core/tests)/
      language: system
      types: [python]
      args:
        - --ignore-patterns=venv
        - --disable=import-error
        - --disable=too-few-public-methods

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        exclude: ^migrations/
        args: [ --py311-plus ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: ^migrations/
        args:
          - --max-line-length=150

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^migrations/

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
