services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    command: -c 'max_connections=200' # Solve max_connections problem. https://stackoverflow.com/a/54484269/1019455
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: debug
      POSTGRES_DB: mydb
