"""Add constraint (identifier, id)

Revision ID: 0124c424c618
Revises: c0e693619289
Create Date: 2024-04-29 12:33:46.755408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0124c424c618'
down_revision: Union[str, None] = 'c0e693619289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'currenttaskcontent', ['identifier', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currenttaskcontent', type_='unique')
    # ### end Alembic commands ###
